name: Create debian package

env:
  DPKG: ${{github.event.repository.name}}_${{github.sha}}-${{github.run_number}}
  DPKG_NAME: "${{github.event.repository.name}}.deb"

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Create package structure
        run: |
          mkdir $DPKG
          cd $DPKG
          mkdir -p DEBIAN usr/local/bin usr/local/share/gfind usr/local/share/applications

      - name: Copy stuff inside
        run: |
          cp deb_control $DPKG/DEBIAN/control
          cp gfind $DPKG/usr/local/bin/
          chmod +x $DPKG/usr/local/bin/*
          cp -r share/* $DPKG/usr/local/share/gfind/
          cp LICENSE $DPKG/usr/local/share/gfind/
          cp README.md $DPKG/usr/local/share/gfind/
          cp gfind.desktop $DPKG/usr/local/share/applications/

      - name: Create deb package
        run: |
          dpkg-deb -Zxz --root-owner-group --build $DPKG $DPKG_NAME
          # Update DPKG_NAME using dpkg-name command
          echo "DPKG_NAME=$(dpkg-name -o $DPKG_NAME |awk -F' ' '{print $6}' |xargs echo |cut -d'/' -f2-)" >> $GITHUB_ENV

      - name: Upload deb as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{env.DPKG_NAME}}
          path: ${{env.DPKG_NAME}}
