name: Create debian package

env:
  versionName: ${{github.sha}}-${{github.run_number}}

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Test
        run: |
          export pkgName="${{github.event.repository.name}}_${{env.versionName}}_all.deb"
          echo "Hello: $pkgName"
