name: Create debian package

env:
  versionName: ${{github.sha}}-${{github.run_number}}
  pkgName: ${{github.event.repository.name}}_${versionName}_all.deb

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Test
        run: |
          echo "Hello: $pkgName"
